### ISSUE TITLE
SystemError: This module can only be run on a Raspberry Pi!

### ISSUE THREAD

**Issue by hosnerm** [metachris/RPIO#111]
Hi everyone 

i tried to run the example3_pwm_servo.py on my Raspberry 3B+ and it gave me the following error when trying to launch the python file : 

   `Traceback (most recent call last):
     File "example3_pwm_servo.py", line 1, in <module>
       from RPIO import PWM
     File "/home/pi/.local/lib/python2.7/site-packages/RPIO/__init__.py", line 115, in <module>
       import RPIO._GPIO as _GPIO
   SystemError: This module can only be run on a Raspberry Pi!`

Could it be that this has to do with using the Rpi 3B+?  
I looked through issues #78 #53 #86 and #106 and tried the solutions that were proposed and verified in there but they did not help. 

Any help would be greatly appreciated!

**Comment by bdn76** [comment]
+1

**Comment by saberbit** [comment]
+1

**Comment by hosnerm** [comment]
by using the pigpio library from here http://abyz.me.uk/rpi/pigpio/index.html i got it to work without any jitter on the servo, think this makes quite a good alternative for all who are struggling with this library. 
maybe you guys want to check it out as well

**Comment by johnroyer** [comment]
I use RPIO version 2. This problem is still exists.

```bash
wget https://github.com/metachris/RPIO/archive/v2.zip
```

----

hardware information
- Raspberry Pi 3 Model B+ (wifi enabled)
- `uname -a` : `Linux pi3-savage 4.15.0-1040-raspi2 #43-Ubuntu SMP PREEMPT Tue Jun 25 10:43:11 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux`
- I run the program inside `virtualenv`
