### ISSUE TITLE
RPIO-0.10.0-py3.5-linux-armv7l.egg SystemError: This module can only be run on a Raspberry Pi!

### ISSUE THREAD

**Issue by ab1vl** [metachris/RPIO#121]
Installed above using: 
sudo apt-get install python-setuptools
$ sudo easy_install -U RPIO
from RPIO install instructions for Raspberry Pi

SystemError: This module can only be run on a Raspberry Pi!

Pi 3B+ running Stretch with latest update/upgrades.  The above is parsed from the python error line  generated by trying to import RPIO.PWM.  I also tried appending an explicit path extension in Mu editor but that failed as well.

**Comment by ab1vl** [comment]
Additional finding: trying to run rpio-curses on same Pi 3B+:
pi@raspberrypi:~ $ rpio-curses
Script not started as root. Running sudo...
Traceback (most recent call last):
  File "/usr/local/bin/rpio-curses", line 4, in <module>
    __import__('pkg_resources').run_script('RPIO==0.10.0', 'rpio-curses')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/RPIO-0.10.0-py3.5-linux-armv7l.egg/EGG-INFO/scripts/rpio-curses", line 74, in <module>
    import RPIO
  File "/usr/local/lib/python3.5/dist-packages/RPIO-0.10.0-py3.5-linux-armv7l.egg/RPIO/__init__.py", line 115, in <module>
    import RPIO._GPIO as _GPIO
SystemError: This module can only be run on a Raspberry Pi!
pi@raspberrypi:~ $ sudo rpio-curses
Traceback (most recent call last):
  File "/usr/local/bin/rpio-curses", line 4, in <module>
    __import__('pkg_resources').run_script('RPIO==0.10.0', 'rpio-curses')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/RPIO-0.10.0-py3.5-linux-armv7l.egg/EGG-INFO/scripts/rpio-curses", line 74, in <module>
    import RPIO
  File "/usr/local/lib/python3.5/dist-packages/RPIO-0.10.0-py3.5-linux-armv7l.egg/RPIO/__init__.py", line 115, in <module>
    import RPIO._GPIO as _GPIO
SystemError: This module can only be run on a Raspberry Pi!

probably same root cause but perhaps an additional clue
