### ISSUE TITLE
Model data doesn't exist for the RPi B+ in the MODEL_DATA dictionary. 

### ISSUE THREAD

**Issue by bmcgonigle** [metachris/RPIO#51]
root@raspberrypi ~ #rpio-curses 
Traceback (most recent call last):
  File "/usr/local/bin/rpio-curses", line 93, in <module>
    "Maker: %s") % RPIO.sysinfo()
  File "/usr/local/lib/python2.7/dist-packages/RPIO/**init**.py", line 183, in sysinfo
    return (RPI_REVISION_HEX,) + MODEL_DATA[RPI_REVISION_HEX.lstrip("0")]
KeyError: '10'

Looks like the model data doesn't exist for the B+ in the MODEL_DATA dictionary. 

 MODEL_DATA = {
     '2': ('B', '1.0', 256, '?'),
     '3': ('B', '1.0', 256, '?'),
     '4': ('B', '2.0', 256, 'Sony'),
     '5': ('B', '2.0', 256, 'Qisda'),
     '6': ('B', '2.0', 256, 'Egoman'),
     '7': ('A', '2.0', 256, 'Egoman'),
     '8': ('A', '2.0', 256, 'Sony'),
     '9': ('A', '2.0', 256, 'Qisda'),
     'd': ('B', '2.0', 512, 'Egoman'),
     'e': ('B', '2.0', 512, 'Sony'),
     'f': ('B', '2.0', 512, 'Qisda')
 }

I'm running python 2.7 on the latest raspian on a Raspberry Pi B+.

**Comment by perrygeo** [comment]
Same problem here. Duplicate of #49

**Comment by braveheartwilliam** [comment]
I had to update this file with additional table entries below.  Don't presume to know where in the package this update should occur.  Once updated rpio-curses worked and rpio --sysinfo returns correct info for my B+.

/usr/local/lib/python2.7/dist-packages/RPIO-0.10.1-py2.7-linux-armv6l.egg/RPIO/__init__.py

Here is the updated table best I could do for the RPi 2.

MODEL_DATA = {
    '2': ('B', '1.0', 256, '?'),
    '3': ('B', '1.0', 256, '?'),
    '4': ('B', '2.0', 256, 'Sony'),
    '5': ('B', '2.0', 256, 'Qisda'),
    '6': ('B', '2.0', 256, 'Egoman'),
    '7': ('A', '2.0', 256, 'Egoman'),
    '8': ('A', '2.0', 256, 'Sony'),
    '9': ('A', '2.0', 256, 'Qisda'),
    'd': ('B', '2.0', 512, 'Egoman'),
    'e': ('B', '2.0', 512, 'Sony'),
    'f': ('B', '2.0', 512, 'Qisda'),
    '10': ('B+', '1.0', 512, 'Sony'),
    '11': ('Compute Module', '1.0', 512, 'Sony'),
    '12': ('A+', '1.0', 256, 'Sony'),
    '13': ('2 B', '1.0', 512, '??')
}

**Comment by braveheartwilliam** [comment]
File should be 

"/usr/local/lib/python2.7/dist-packages/RPIO-0.10.1-py2.7-linux-armv6l.egg/RPIO/__init__.py"

**Comment by braveheartwilliam** [comment]
should show "underscore" "underscore" "init" "underscore" underscore" .py as the file name.  Underscores disappear when saved.

**Comment by lurch** [comment]
> Underscores disappear when saved.

Enclosing your text between backticks marks it as 'code' and then underscores get preserved, like this: `/usr/local/lib/python2.7/dist-packages/RPIO-0.10.1-py2.7-linux-armv6l.egg/RPIO/__init__.py`

**Comment by lurch** [comment]
...and see also #35 which includes additional fixes for the new 40-pin header on the B+, so the same changes will need to be made in order for RPIO to 'properly' support the A+ (and PiZero).
