### ISSUE TITLE
rpio-curses on Raspbery Pi A+

### ISSUE THREAD

**Issue by PetrJakes** [metachris/RPIO#65]
rpio-curses command issued on Raspbery Pi A+ ends with following error:

root@kroko:/automat# rpio-curses
Traceback (most recent call last):
  File "/usr/local/bin/rpio-curses", line 5, in <module>
    pkg_resources.run_script('RPIO==0.10.0', 'rpio-curses')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/RPIO-0.10.0-py2.7-linux-armv6l.egg/EGG-INFO/scripts/rpio-curses", line 93, in <module>
    "Maker: %s") % RPIO.sysinfo()
  File "/usr/local/lib/python2.7/dist-packages/RPIO-0.10.0-py2.7-linux-armv6l.egg/RPIO/__init__.py", line 183, in sysinfo
    return (RPI_REVISION_HEX,) + MODEL_DATA[RPI_REVISION_HEX.lstrip("0")]
KeyError: '12'

**Comment by jhburkhard** [comment]
See issue #51 Model data doesn't exist for the RPi B+ in the MODEL_DATA dictionary
