### ISSUE TITLE
v2 beta: Script rpio fails on Pi3

### ISSUE THREAD

**Issue by Thad-BC** [metachris/RPIO#99]
Running script RPIO/source/scripts/rpio with option --sysinfo results in an error:
```
pi@raspberrypi:~/RPIO/RPIO/source/scripts $ rpio --sysinfo
Script not started as root. Running sudo...
Traceback (most recent call last):
  File "/usr/local/bin/rpio", line 4, in <module>
    __import__('pkg_resources').run_script('RPIO==2.0.0-beta1', 'rpio')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/RPIO-2.0.0_beta1-py2.7-linux-armv7l.egg/EGG-INFO/scripts/rpio", line 353, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/RPIO-2.0.0_beta1-py2.7-linux-armv7l.egg/EGG-INFO/scripts/rpio", line 346, in main
    
  File "build/bdist.linux-armv7l/egg/RPIO/__init__.py", line 186, in sysinfo
KeyError: 'a22082'
```
This apparently results from not including the recent hardware versions in the checking code.
This should be updated to recognize the RPi3.
Also, it would be helpful to print a formatted message if run on unrecognized hardware.
I plan to submit a PR for this.

Environment:
RPIO version: v2 (2016.06.02: 07c776f634f3c5ba536490763fbf7cc5e9f94572)
Hardware: RPi 3, BCM2709, rev. a22082
OS: Raspbian GNU/Linux 8
Python: 2.7.9

**Comment by JamesGKent** [comment]
i had to fork and patch this lately so i could use it on my pi zero w, i updated the list with all the currently known versions of the pi, you can give it a try here: [https://github.com/JamesGKent/RPIO/tree/v2](https://github.com/JamesGKent/RPIO/tree/v2)
